Web.App/Controllers/Base/BaseReportController.cs
using Microsoft.Reporting.WebForms;
using Services.Web.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Web.App.Controllers
{
    public class BaseReportController : BaseController
    {
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public ActionResult Index(VMReport model)
        //    {
        //        Response.Redirect(CompileUrl(model),true);
        //        return null;
        //        //return Redirect(CompileUrl(model));
        //        //return Json(CompileUrl(model));
        //    }
        //    protected string ReportName { get; set; }
        //    private string CompileUrl(VMReport model){

        //        model.createdBy = Session["UserFullName"].ToString();
        //        ReportSettings rs = new ReportSettings(UserId);
        //        model.imagesource = rs.ReportLogoUrl;
        //        //string.Format("{0}/Pages/ReportViewer.aspx?{1}{2}",reportserver,reportfolder,parameters);
        //        //foreach property in model, generate "&propertyname="propertyvalue
        //        string properties = "";
        //        foreach (System.ComponentModel.PropertyDescriptor prop in System.ComponentModel.TypeDescriptor.GetProperties(typeof(VMReport)))
        //            //table.Columns.Add(prop.Name, Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType);
        //            if(prop.GetValue(model) != null)
        //            properties += string.Format("&{0}={1}", prop.Name, prop.GetValue(model));

        //        return string.Format("{0}/Pages/ReportViewer.aspx?%2f{1}/{2}{3}", rs.ReportServer,rs.ReportFolder, ReportName, properties);
        //    }
        public BaseReportController():base()
        {
            ApplySecurity = false;
        }
        public ActionResult ReportContent(string reportName, Dictionary<string, string> pparameters)
        {
            ReportViewer reportViewer = new ReportViewer();
            ReportSettings rs = new ReportSettings();

            reportViewer.ProcessingMode = ProcessingMode.Remote;
            reportViewer.ServerReport.ReportPath = string.Format("/{0}/{1}", rs.ReportFolder, reportName);
            reportViewer.ServerReport.ReportServerUrl = new Uri(rs.ReportServer);
            reportViewer.Height = new Unit(400, UnitType.Pixel);
            reportViewer.Width = new Unit(100, UnitType.Percentage);

            pparameters.Add("imagesource", rs.ReportLogoUrl);
            pparameters.Add("createdBy", Session["UserFullName"].ToString());

            IEnumerable<ReportParameter> rps = new List<ReportParameter>();
            if (pparameters != null)
            {
                pparameters.Remove("action");
                pparameters.Remove("controller");
                rps = rps.Concat(pparameters.Where(v => !string.IsNullOrWhiteSpace(v.Value)).Select(v => new ReportParameter(v.Key, v.Value.Split(new char[] { ',' }))));
            }
            
            if (rps.Count() > 0)
                reportViewer.ServerReport.SetParameters(rps);

            return PartialView(reportViewer);
        }

    }
}

Web.App/Views/Shared/_ActionButtons.cshtml
@model string
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-3 col-md-9">
            <a id="indexBtn" href='@Url.Action("Index", Model)' class="btn btn-outline green button-previous">
                <i class="fa fa-angle-left"></i> @ZM.UI.Back
            </a>
            <a id="backBtn" href="javascript:;" class="btn default button-previous" style="display:none">
                <i class="fa fa-angle-left"></i> @ZM.UI.Back
            </a>
            <a id="continueBtn" href="javascript:;" class="btn btn-outline green button-next" style="">
                @ZM.UI.Continue
                <i class="fa fa-angle-right"></i>
            </a>
            <a id="submitBtn" href="javascript:;" class="btn green button-submit" style="display:none;">
                @ZM.UI.Submit
                <i class="fa fa-check"></i>
            </a>

        </div>
    </div>
</div>

Web.App/Views/Shared/_FileUpload.cshtml
@model string

    <div style="margin-left: 20px; margin-right: 20px" class="col-md-4">
        <img id="fileImg" width="150" style="width:-webkit-fill-available;" height="150" class="img-responsive pic-bordered" src="@Model" onerror="this.onerror=null;this.src='@Url.Content("~/Images/defaultUserIcon.png")';" />

        @(Html.Kendo().Upload()
                .Name("PictureFile")
                .ShowFileList(false)
                .Events(e => e.Select("onSelect"))
                .Multiple(false)
                .Validation(v => v
                .AllowedExtensions(new string[] { ".gif", ".jpg", ".png" })
                .MaxFileSize(5 * 1000 * 1000)
                )

        )

        <div style="margin-bottom:20px" class="clearfix margin-top-10">
            <span class="label label-danger"> NOTE! </span>
            <span> Images supported are: JPG, GIF, PNG </span>
        </div>
    </div>

<script src="~/Scripts/file/fileUpload.js"></script>

Web.App/Views/Shared/_FilesUpload.cshtml
<script type="text/x-kendo-tmpl" id="template">
    # for (var i = 0; i < data.length; i++){ #
    <div class="vlistTemplate #:data[i].Selected? 'k-state-selected' :''#" id="#:i#">
        <img class="selectedImg" src="#:data[i].fileContent#" />
        <span id="#:i#Close" class="k-icon k-i-close removeimage" style="font-size:25px;top:0;right:0;position:absolute;color:gray;z-index:1000;cursor:pointer"></span>

    </div>
    # } #
</script>
<div id="images" class="clearfix float-left">
</div>

<div id="loading" style="display:none">
    <img id="loading-image" src="~/images/loading.gif" />
</div>
<div id="arrowDiv clearfix">
    <button id="leftBtn" type="button" class="btn btn-primary mt-ladda-btn ladda-button btn-circle">
        <span class="ladda-label">
            <i class="icon-arrow-left"></i>
        </span>
    </button>
    <span class="ladda-label" style="padding-left:32%;">
        <strong>  First image </strong> will considered the <strong> Logo  </strong> image
    </span>
    <button id="rightBtn" type="button" class="btn btn-primary mt-ladda-btn ladda-button btn-circle pull-right">
        <span class="ladda-label">
            <i class="icon-arrow-right"></i>
        </span>
    </button>
</div>
<div class="demo-section k-content wide" style="margin: 10px ">
    @(Html.Kendo().Upload()
     .Name("files")
     .Events(e => e.Progress("onUpload").Select("onSelect"))
     .ShowFileList(false)
     .Validation(validation =>
     {
     validation.AllowedExtensions(new string[]
     { ".jpg", ".jpeg", ".png", ".bmp", ".gif", ".png" });
     validation.MaxFileSize(5000 * 1024);
     })

    )
</div>

Web.App/Views/Shared/_Loading.cshtml
<link href="~/Content/appStyles/loading.css" rel="stylesheet" />
<div id="loading" style="display:none">
    <img id="loading-image" src="~/images/loading.gif" />
</div>

Web.App/Views/Shared/_ReportLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <div class="portlet light ">
            @Html.FormHeaderWithButtons((string)ViewBag.Title)
            <!-- tile body -->
            <div class="portlet-body form">
                <div class="form-body">
                    @RenderBody()
                    @Html.FormActionsRow(new FormActionButton { Label = "Render", OtherProperties = "onclick=\"showReport()\"", Type = "btn" })
                </div>
            </div>
            <!-- /tile body -->
        </div>
    </div>
    <div class="col-md-8">
        <div id="ReportContent" style="width: 100%;">
        </div>
    </div>
</div>
<script type="text/javascript">
	var getParameters = function () {
		return {
		};
	};

	function showReport() {
		kendo.ui.progress($("#ReportContent"), true);
		$("#ReportContent").load('@Url.Action("ReportContent","BaseReport")', {
			reportName: "@ViewBag.ReportName",
            pparameters: getParameters()
		}, function (response, status, xhr) {
			if (status == "error") {
				alert('Error802');
				kendo.ui.progress($("#ReportContent"), false);
			}
		});
	};
</script>
@RenderSection("Scripts", false)